## NumPy - Numerical Python

In [ ]:
import numpy as np

# NumPy Arrays  
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
# math works element-wise
print(a + 1)      # [2, 3, 4]
print(a * 2)      # [2, 4, 6]

# Shape
a.shape   

# Shape - 2D Arrays (think rows=samples and columns=features)
y = np.array([[1, 2], [3, 4], [5, 6]])
y.shape    # (3, 2)


[1 2 3 4 5 6]
[2 3 4 5 6 7]
[ 2  4  6  8 10 12]


(3, 2)

In [ ]:
print(np.mean(a))
print(np.sum(a))
print(np.linalg.norm(a))

3.5
21
9.539392014169456
