## NumPy - Numerical Python

In [2]:
import numpy as np

# NumPy Arrays (ndarray: N-dimensional array)
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

# Math works element-wise
print(arr + 1)      
print(arr * 2)     


[1 2 3 4 5 6]
[2 3 4 5 6 7]
[ 2  4  6  8 10 12]


In [ ]:
# ARRAY ATTRIBUTES

# arr.shape - size of each dimension
print(arr.shape)

# Shape of 2D Arrays 
matrix = np.array([[1, 2], [3, 4], [5, 6]])
matrix.shape    # (3, 2)

# arr.ndim - number of dimensions
# arr.size - total number of elements
# arr.dtype - data type 

(6,)

In [ ]:
# Creating Special Arrays

# Zeros, Ones, Full
print(np.zeros(5))
print(np.ones((2,3)))
print(np.full((2,2), 6))

print()

# Ranges
print(np.arange(0, 10, 2)) # like range()
print(np.linspace(0, 1, 5)) # evenly spaced

print()

# Identity Matrix
print(np.eye(3))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]]

SOHAN
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Reshaping Arrays
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# DATA TYPES & CASTING 
arr = np.array([1, 2, 3], dtype=float)
print(arr)
arr.astype(int)

[1. 2. 3.]


array([1, 2, 3])

In [34]:
# INDEXING & SLICING
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[-1])

print(arr[1:3])

print()

# 2D Indexing
matrix = np.array([[1, 2, 3],
[4, 5, 6]])

(matrix[0, 1]) # row 0, col 1
matrix[:, 1]

10
40
[20 30]



array([2, 5])

In [ ]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3]

arr[(arr > 2) & (arr < 5)]

In [36]:
# Array Operations (Vectorization)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

# Comparison
print(a > 2)

[5 7 9]
[ 4 10 18]
[1 4 9]
[False False  True]


In [ ]:
# Broadcasting - dimensions must be equal or one of them must be 1
arr = np.array([1, 2, 3])
print(arr + 10)

matrix = np.array([[1,2,3],[4,5,6]])
matrix + np.array([10, 20, 30])

In [ ]:
# Aggregate Functions
arr = np.array([1, 2, 3, 4])

print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())

print(matrix.sum(axis=0)) # columns
print(matrix.sum(axis=1)) # rows


# Reshape Array
arr = np.arange(6)
arr.reshape((2,3))

matrix.flatten()

10
2.5
1
4
1.118033988749895
[5 7 9]
[ 6 15]


In [ ]:
# Stacking
a = np.array([1,2])
b = np.array([3,4])

np.vstack([a,b])
np.hstack([a,b])

# Splitting
arr = np.arange(10)
np.split(arr, 5)

In [ ]:
# Copy vs View
a = np.array([1,2,3])
b = a
b[0] = 99
a

c = a.copy()

In [ ]:
# Random Numbers
np.random.rand(3)
np.random.randn(3)
np.random.randint(0, 10, size=5)

np.random.seed(42)

In [ ]:
# Math
print(np.mean(arr))
print(np.sum(arr))
#print(np.linalg.norm(arr))


3.5
21


In [7]:
# Dimensions & New Axes - converting a 1D vector into a 2D row or column matrix
a = np.array([1, 2, 3])

print( a[np.newaxis, :] ) # Row vector (1, 3)
print( a[:, np.newaxis] ) # Column vector (3, 1)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
# Array Concatenation

# Combining multiple arrays into one
# Concatenate along first axis, by default 
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


print( np.concatenate([grid, grid]), "\n" )
print( np.concatenate([grid, grid], axis=1), "\n")
print( np.concatenate([grid, grid, grid]), "\n" )


# Stacking Arrays
# Splitting Arrays

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]] 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

