## NumPy - Numerical Python

In [1]:
# %pip install pandas matplotlib seaborn scikit-learn scipy statsmodels notebook jupyterlab

In [2]:
# NumPy operations are significantly faster than Python list operations as well as memory efficient
import numpy as np

# NumPy Arrays (ndarray: N-dimensional array)
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

# Math works element-wise
print(arr + 1)      
print(arr * 2)     


[1 2 3 4 5 6]
[2 3 4 5 6 7]
[ 2  4  6  8 10 12]


In [3]:
# ARRAY ATTRIBUTES

# arr.shape - size of each dimension
print(arr.shape)

# Shape of 2D Arrays 
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.shape)    # (3, 2)

print(matrix.ndim)
# arr.ndim - number of dimensions
# arr.size - total number of elements
# arr.dtype - data type 

(6,)
(3, 2)
2


In [4]:
# Creating Special Arrays

# Zeros, Ones, Full
print("Creates array filled with 0's: \n", np.zeros(5))
print("Creates 2x3 array filled with 1's \n", np.ones((2,3)))
print("Creates 2x2 array filled with 6's: \n", np.full((2,2), 6))

print()

# Ranges
print("This is arrange", np.arange(0, 10, 2)) # like range()
print("This is linspace", np.linspace(0, 1, 5)) # evenly spaced

print()

# Identity Matrix
print("This is an identity matrix \n", np.eye(3))

Creates array filled with 0's: 
 [0. 0. 0. 0. 0.]
Creates 2x3 array filled with 1's 
 [[1. 1. 1.]
 [1. 1. 1.]]
Creates 2x2 array filled with 6's: 
 [[6 6]
 [6 6]]

This is arrange [0 2 4 6 8]
This is linspace [0.   0.25 0.5  0.75 1.  ]

This is an identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Reshaping Arrays
grid = np.arange(1, 10).reshape((3, 3)) # Reshape as 3x3
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# DATA TYPES & CASTING 
arr = np.array([1, 2, 3], dtype=float)
print(arr)
arr.astype(int)

[1. 2. 3.]


array([1, 2, 3])

In [7]:
# INDEXING & SLICING
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[-1])

print(arr[1:3])

print()

# 2D Indexing
matrix = np.array([[1, 2, 3],
[4, 5, 6]])

(matrix[0, 1]) # row 0, col 1
print("1st index of each row: ", matrix[:, 1])

10
40
[20 30]

1st index of each row:  [2 5]


In [8]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])

print(arr[(arr > 2) & (arr < 5)])

[4 5]
[3 4]


In [9]:
# Array Operations (Vectorization)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

# Comparison
print(a > 2)

[5 7 9]


[ 4 10 18]
[1 4 9]
[False False  True]


In [10]:
# Broadcasting - dimensions must be equal or one of them must be 1
arr = np.array([1, 2, 3])
print(arr + 10)

matrix = np.array([[1,2,3],[4,5,6]])
matrix + np.array([10, 20, 30])

# Broadcasting Rules:
# Rule 1: If two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side
# Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape
# Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised

[11 12 13]


array([[11, 22, 33],
       [14, 25, 36]])

In [11]:
# Aggregate Functions
arr = np.array([1, 2, 3, 4])

# for NaN-safe versions just add nan in front, i.e arr.nansum()
print("This is the sum: \n", arr.sum()) # Sum of elements
print("This is the average: \n", arr.mean()) # Average of elements
print("This is the min value: \n", arr.min()) # Min value
print("This is the max value: \n", arr.max()) # Max value
print("This is the standard deviation: \n", arr.std(), "\n") # Standard deviation

# axis=0 "Collapse the rows" (Compute COLUMN statistics)
# axis=1 "Collapse the columns" (Computer ROW statistics)
mat = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("This is the average of the columns: \n", mat.mean(axis=0))

matrix2 = np.array([[1,2,3],
                   [4,5,6]])

print("\n Sum down the columns: \n", matrix2.sum(axis=0)) # columns
print("Sum the rows: \n", matrix2.sum(axis=1)) # rows

print("This converts a 2D array into a 1D array: \n", matrix2.flatten())

This is the sum: 


 10
This is the average: 
 2.5
This is the min value: 
 1
This is the max value: 
 4
This is the standard deviation: 
 1.118033988749895 

This is the average of the columns: 
 [4. 5. 6.]

 Sum down the columns: 
 [5 7 9]
Sum the rows: 
 [ 6 15]
This converts a 2D array into a 1D array: 
 [1 2 3 4 5 6]


In [12]:
# AXIS RULE
print('axis=0 (Along the Columns): Think of this as "running down the vertical spine." If you take the mean at axis=0, you are collapsing the rows to get a result for each column. \n')
print('axis=1 (Along the Rows): Think of this as "running across the horizontal line." If you take the mean at axis=1, you are collapsing the columns to get a result for each row. \n')

# shape = (rows, columns)
# axis=0 → rows gets collapsed
# axis=1 → columns get collapsed 

axis=0 (Along the Columns): Think of this as "running down the vertical spine." If you take the mean at axis=0, you are collapsing the rows to get a result for each column. 

axis=1 (Along the Rows): Think of this as "running across the horizontal line." If you take the mean at axis=1, you are collapsing the columns to get a result for each row. 



In [13]:
# Stacking
a = np.array([1,2])
b = np.array([3,4])

print("This is vertical stack; \n", np.vstack([a,b]))
print("This is hprizontal stack \n", np.hstack([a,b]))

# Splitting
arr = np.arange(10)
print("This is splitting: \n", np.split(arr, 5)) # Break array into sub-arrays and indices list the split points

This is vertical stack; 
 [[1 2]
 [3 4]]
This is hprizontal stack 
 [1 2 3 4]
This is splitting: 
 [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [14]:
# Copy vs View
a = np.array([1,2,3])
b = a
b[0] = 99
a

c = a.copy()

In [15]:
# Random Numbers
np.random.rand(3)
np.random.randn(3)
np.random.randint(0, 10, size=5)

np.random.seed(42)

In [16]:
# Math
print(np.mean(arr))
print(np.sum(arr))
#print(np.linalg.norm(arr))

4.5
45


In [17]:
# Dimensions & New Axes - converting a 1D vector into a 2D row or column matrix
a = np.array([1, 2, 3])
# Shape: (3,) - This is just a flat list.

print("Convert to row vector: \n", a[np.newaxis, :] ) # Row vector (1, 3)
print("Convert to column vector: \n", a[:, np.newaxis] ) # Column vector (3, 1)

# np.newaxis is a tool used to increase the dimension of an existing array by one, 
# effectively turning a 1D vector into a 2D row or column matrix

Convert to row vector: 
 [[1 2 3]]
Convert to column vector: 
 [[1]
 [2]
 [3]]


In [18]:
# Array Concatenation

# Combining multiple arrays into one
# Concatenate along first axis, by default 
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


print( np.concatenate([grid, grid]), "\n" )
print( np.concatenate([grid, grid], axis=1), "\n")
print( np.concatenate([grid, grid, grid]), "\n" )

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]] 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 



In [19]:
# Boolean Masks - Using comparsion operators on arrays returns a Boolean array
x = np.array([1,2,3,4,5])

print(x < 3)
print(x > 3)
print(x <= 3)
print(x >= 3)
print(x != 3)
print(x == 3)

[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [20]:
# LINEAR ALGEBRA
A = np.array([3, 4])
B = np.array([5, 6])

# Dot Product - Modern Python way (@ symbol)
result = A @ B 
print("Modern way to compute dot product: \n", result)

# Old school NumPy way
result_alt = np.dot(A, B)
print("Old school way: \n", result_alt)

# Transpose
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array: \n", A)
print("Transposed array (swap rows and columns): \n", A.T)

Modern way to compute dot product: 
 39
Old school way: 
 39
Original array: 
 [[1 2 3]
 [4 5 6]]
Transposed array (swap rows and columns): 
 [[1 4]
 [2 5]
 [3 6]]


In [21]:
# LINEAR ALGEBRA CONTINUED
from numpy import linalg # (needed for linalg.iv, linalg.eig, etc)

# Inverse - A x A^-1 = I
# Inverse is the matrix "equivalent" of division. If A • x = B, then x = A^-1 • B
X = np.array([[1,2],[3,4]])
X_inv = linalg.inv(X)
print("This is inverse of matrix A: \n", X_inv)
# Determinate of X CANNOT be equal to 0, otherwise the matrix cannot be inverted
# (m x n) x (n x p) = (m x p)

# Eigenvalues and Eigenvectors - used in PCA (principal component analysis) to find the most important "directions" in data
# Definition: Av = λv
# v = eigenvector (direction)
# λ = eigenvalue (scaling factor)

# Eigenvectors: Represent the "direction"
# Eigenvalues: Represent the "magnitude" or importance
print("\n")
A = np.array([[4,2],
              [1,3]])

eigenvalues, eigenvectors = linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("\n")

# Matrix Rank - the maximum number of linearly independent rows or columns, representing the dimension of the vector space spanned by them
# Counts non-zero rows in Row Echelon Form (REF)
A = np.array([[1,2],
              [2,4]])
rank = linalg.matrix_rank(A)
print("Matrix Rank:", rank)

This is inverse of matrix A: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Matrix Rank: 1


In [22]:
# Solving Linear Systems
# Instead of x = A^-1 b
# Use Ax = b

A = np.array([[3,1],
              [1,2]])

b = np.array([9,8])

x = linalg.solve(A,b)

print(x)

[2. 3.]


In [23]:
# Machine Learning Linear Algebra Stack (most used so make sure you understand and know them):
'''
Vectors
Matrices
Dot/Cross Products
Matrix Addition/Subtraction/Multiplication/Division
Transpose
Eigenvalues/Eigenvectors
SVD
Norms
'''

'\nVectors\nMatrices\nDot/Cross Products\nMatrix Addition/Subtraction/Multiplication/Division\nTranspose\nEigenvalues/Eigenvectors\nSVD\nNorms\n'